### PR TITLE
BL-553-fe-add-style-guide-fonts-to-app-style-defaults

### PR DESCRIPTION
**Pull request by MaxwellChrist**
## Description

The purpose of our ticket was to import the features from the style guide into our project. Using the assets from the style guide, we added the assets into an asset folder. We renamed all of the assets and separated each to their separate folders. Afterwards we knew these were going to be the default styling, so we created global variables to be able to use/reference them in different sections of the app. Lastly we imported the CSS file containing the global variables into index.js file.

#### Video Link

[Loom Video](https://www.loom.com/share/61ee57e5367d4e019f5a20eca59f3ccc)

#### Jira Link

<blockquote class="trello-card"><a href="https://bloomtechlabs.atlassian.net/jira/software/c/projects/BL/boards/8?modal=detail&selectedIssue=BL-553">Feature: added style guide fonts to app style defaults</a></blockquote>

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by attaris978 — APPROVED** [review]
Total. Boss. Work. The idea of MVP is improving the product enough to release it per CICD. While the intricacies of craco-less may have cost you hours (many hours -- I am well aware of how much time you put into this), you managed to find a perfectly viable workaround and even took it to the next level by facilitating future adherence to styles. Truly admirable dedication and thoroughness.

**Review by VWashingtonCoder — DISMISSED** [review]
I think it was a great idea to make all of the font styles into global variables for reusability throughout multiple components. We will have to look into seeing if we can convert it to LESS but I see little problem proceeding with CSS at the moment.

**Review by EricMarshallLambert — DISMISSED** [review]
I appreciate the clarity that reusability brings to a code base. 

Will not using Less cause issues at the moment? I am not very familiar with it, and it seems to be something your are learning.

**Review by SafiaOmar — DISMISSED** [review]

**Review by vbrambila2 — APPROVED** [review]
Great job with adding the less files, everything seemed straight forward to me

**Review by attaris978 — APPROVED** [review]
I've already gone through these changes and provided my feedback, however excellent work resolving merge conflicts and getting this ready to merge into main. I am (re) approving now, which will give you enough to go forward. Thanks for your ridiculous hours trying to figure out the complexities of less, css, and fonts -- way more than 3 points worth of work ; )

**Review by Joshmclemore — APPROVED** [review]
Awesome work with the logos and fonts. This will help a great deal down the line! Agreed. More than 3 points worth of work.

**Comment by paulstgermain** [comment]
> I've already gone through these changes and provided my feedback, however excellent work resolving merge conflicts and getting this ready to merge into main. I am (re) approving now, which will give you enough to go forward. Thanks for your ridiculous hours trying to figure out the complexities of less, css, and fonts -- way more than 3 points worth of work ; )

@attaris978 Noted! I'm upgrading this set of work from 3 to 5 points - I know just how much work it takes to understand and work with `craco-less`, much less for the first time! Great work here in totality - and to the whole team, excellent job resolving all these conflicts so quickly!

**Pull request merged**
