### PR TITLE
Feature/bl 69 pagination

### PR DESCRIPTION
**Pull request by billydean**
## Description

Imported a page navigation menu from ANT.
 - indicates currently displayed range of total results
 - may include option to jump to particular page, depending on the user's printing/exporting options
 - chose the 'mini' version to align with current style docs

Page size is determined by *initial window size on first render/mount*. Method may change as we continue coordinating between front and back end. Until PageNav (the component in question) has its appropriate parent, we set up a temporary container with the necessary hooks to read and pass the window size to PageNav.

As a bonus -- I took a crack at gutting a lot of the files and folders from the SPA template unnecessary for our project.

#### Video Link

https://www.loom.com/share/62588c75353744a4be0f0af46efd5533

#### Jira Link

<blockquote class="trello-card"><a href="https://bloomtechlabs.atlassian.net/browse/BL-69?atlOrigin=eyJpIjoiMzJiYmM2M2Y0YzVkNDFiNmJhNjIzMjdjMGIyMzIxYTkiLCJwIjoiaiJ9">FE: Pagination</a></blockquote>

## Type of change

___Please delete options that are not relevant.___

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [ ] My changes generate no new warnings (see below)
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

N.B. Changes do (sometimes??? not at the moment, for some reason) generate a new warning (Uncaught ReferenceError), but I believe it's because of our makeshift way of detecting/using window size. When PageNav finds its permanent home and parent, we can work it more smoothly into the project's overall state management strategy.

### CODE REVIEW

**Review by attaris978 — APPROVED** [review]
Your pagination addition is readable, clean, and elegantly structured. ⭐
However, your machete skills are even better. Having this weeding-out done before I started on the project would have saved me a tremendous amount of time and energy.

**Review by VWashingtonCoder — DISMISSED** [review]
I like the simplicity of this. It shouldn't be too hard to plug in a few other items such as total items based around the other states set up already in Redux. Great job.

**Review by Jason7jl — COMMENTED** [review]
Great job!

**Review by EstrellaDionis — APPROVED** [review]
Great explanation in the video and the code is clean and easy to understand. Great work!

**Review by XavierTwitty — DISMISSED** [review]
I like how when you change the window size it changes how many pages can been based on the screen size. I also liked how you left comments for the next person on where you think you code should be to give then I better look at your thought process.

**Review by vbrambila2 — APPROVED** [review]
Great job! I like the idea of the user being able to see the total number of items retrieved instead of just the page numbers.

**Review by SafiaOmar — DISMISSED** [review]

**Pull request merged**
