### PR TITLE
BL-571 BugFix/Update-files-containing-JSX-with-.jsx-extension

### PR DESCRIPTION
**Pull request by attaris978**
## Description

This quick-fix bug ticket involved changing any file containing JSX to the appropriate .jsx extension. While .jsx files will seamlessly transpile down to .js, it is nonetheless a part of best practices to name each file depending on its contents. This makes your code more self-documenting, and gives somebody trying to analyze and map out your code a major advantage in figuring out what the purpose of each file is.

#### Video Link

https://www.loom.com/share/088085246843418a9f42c82f4df548aa

#### Jira Link

https://bloomtechlabs.atlassian.net/browse/BL-571?atlOrigin=eyJpIjoiNGUzODJhZGNkMWY5NDYxZWI0NDI4ZTBlYWExZWE5NjUiLCJwIjoiaiJ9

## Type of change

- [ ✅ ] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ✅ ] My code follows the style guidelines of this project
- [ ✅ ] I have performed a self-review of my own code
- [ ✅ ] I have removed unnecessary comments/console logs from my code
- [ ✅ ] My changes generate no new warnings
- [ ✅ ] I have checked my code and corrected any misspellings
- [ ✅ ] No duplicate code left within changed files
- [ ✅ ] Size of pull request kept to a minimum
- [ ✅ ] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by Jason7jl — COMMENTED** [review]
It's a great update.

**Review by MaxwellChrist — APPROVED** [review]
I remember Ryan bringing this up and I didn't think twice about making this change. I certainly agree that from a best practices standpoint, this is something that needed to be done and it was another great idea from Ryan

**Review by SafiaOmar — DISMISSED** [review]
Wow this makes so much sense you truly brought it to life. Great idea and amazing execution Ryan.

**Review by VWashingtonCoder — DISMISSED** [review]
I didn't actually realize the importance of this fully until this breakdown. Great job as usual.

**Review by vbrambila2 — APPROVED** [review]
Thank you for getting this done, the code definitely looks cleaner

**Review by Ricardorouge — APPROVED** [review]
thank you for taking on this massive task

**Pull request merged**
