### PR TITLE
BL-589-fe-add-favicon-assets-to-app

### PR DESCRIPTION
**Pull request by attaris978**
## Description

Used the HRF logo to create a viable image, then used the online favicon generator to create requisite-for-best-practices files, and placed them in the public/favicon folder. And it works.
I also changed the title of the page from "Basic SPA" to "HRF Asylum Report Generator." And that also works.

#### Video Link

https://www.loom.com/share/eb67260c38f04dfc96211894466094d3

#### Jira Link

https://bloomtechlabs.atlassian.net/browse/BL-589?atlOrigin=eyJpIjoiOTFjODNkN2QwY2RmNDRlNWE5M2NmZmJkNDE1OGZiZGUiLCJwIjoiaiJ9

## Type of change

- [ ✅ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ✅ ] My code follows the style guidelines of this project
- [ ✅ ] I have performed a self-review of my own code
- [ ✅ ] I have removed unnecessary comments/console logs from my code
- [ ✅ ] My changes generate no new warnings
- [ ✅ ] I have checked my code and corrected any misspellings
- [ ✅ ] No duplicate code left within changed files
- [ ✅ ] Size of pull request kept to a minimum
- [ ✅ ] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by Ricardorouge — APPROVED** [review]
this definitely looks better than a waffle, that being said I think they mentioned in the stakeholder meeting not to really worry about the favicon but since you already did it looks good!

**Review by MaxwellChrist — APPROVED** [review]
Although I'm gonna miss the waffle, we all knew it had to go sooner or later. Great job on the favicon design

**Review by EricMarshallLambert — APPROVED** [review]
I know they didn't seem to concerned about the favicon, but it is much more appropriate.

Having the title of the page changed feels much more professional when showing off demo's to the stakeholders and I am happy to see it changed.

**Review by Jason7jl — COMMENTED** [review]
It's great.

**Pull request merged**
