### PR TITLE
BL-821 feature / I want to save a visualization I see on screen 

### PR DESCRIPTION
**Pull request by Austin-T-Johnson**
## Description

Added functionality to download visualizations as either PNG or SVG image.

#### Video Link

https://www.loom.com/share/cb185411ad624540a1ebea3d84622801

#### Jira Link

https://bloomtechlabs.atlassian.net/browse/BL-821?atlOrigin=eyJpIjoiMWYyNDI4ZjA2NDRlNDgyZjk0MTY5NmY2M2YwMjI3NzUiLCJwIjoiaiJ9

## Type of change

___Please delete options that are not relevant.___

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by EstrellaDionis — APPROVED** [review]
The code is very lean with great naming conventions which makes everything easy to follow. Great work!

**Comment by Epeng1994** [comment]
Effective variable names and easy implementation for other features to use as well. Looks fantastic!

**Review by andrewgomez1992 — DISMISSED** [review]
Looks good! Very clean and easy to read.

**Review by XavierTwitty — DISMISSED** [review]
Good clean and easy to read code. The video gives a better understanding of the download function.

**Comment by publiminal** [comment]
It looks great so far @Austin-T-Johnson !

feedback / questions : 
1. Image downloaded naming Conventions
Currently : newplot(x).png

Expected : There is no definition no this, but I suggest it could be great to replicate the visualization's title and current date : [visualization_title][at_current_date] (Ex "Total_Asylum_Petitions_2018-2021_at_08_22"

Goal :
- add friendly informative naming 
- Avoid image overwriting on user's download folder or current image duplication 
  
2. Download .SVG only. 
Currently : 2 options available (.svg, .png)
Expected : Not sure what what are image dimensions for .png format .If this takes current pixles from screen, let's think twice how it works on mobile. 
I suggest removing .png and just keeping .svg will be best option

3. Implement as a component 
Currently : Cleverly now works as a util. 
Expected : To improve in a later iteration to import as a component

**Review by publiminal — COMMENTED** [review]
It looks great so far @Austin-T-Johnson !

feedback / questions :

1. Image downloaded naming Conventions
Currently : newplot(x).png

Expected : There is no definition on this, but I suggest it could be great to replicate the visualization's title and current date : [visualization_title][at_current_date] (Ex "Total_Asylum_Petitions_2018-2021_at_08_22")

Goal :

add friendly informative naming
Avoid image overwriting on user's download folder or current image duplication
2. Download .SVG only.
Currently : 2 options available (.svg, .png)
Expected : Not sure what are image dimensions for .png format. If this takes current pixels from screen, let's think twice how it works on mobile.
I suggest removing .png and just keeping .svg will be best option

3. Implement as a component
Currently : Cleverly how now works as a util.

**Review by EstrellaDionis — APPROVED** [review]
Great idea to create styles and then importing them into the necessary pieces, creating easier code to look at.

**Review by XavierTwitty — APPROVED** [review]
I like how you refactored the HeatMapContainer making your divs more semantic by adding classnames to your containers making the code easier to read.

**Review by publiminal — APPROVED** [review]
Kudos !

**Review by AdeShennaike — APPROVED** [review]

**Review by AdeShennaike — COMMENTED** [review]
good stuff

**Review by Epeng1994 — APPROVED** [review]
Looks great!

**Review by EstrellaDionis — APPROVED** [review]
Great changes!

**Comment by mack-gallagher** [comment]
Looks clean and efficient to me! I think routing the default Plot.ly download functions through a bigger, more visible button is a clever solution.

**Review by mack-gallagher — APPROVED** [review]
Looks clean and efficient to me! I think routing the existing Plot.ly download functions through bigger, more visible buttons is a clever solution.

**Review by XavierTwitty — APPROVED** [review]
Good work

**Review by jtorres03 — APPROVED** [review]
Looks great! Love that you added two types of download files.

**Pull request merged**
